### ISSUE TITLE
DR-HSH006S becomes unresponsive after setting state to 'OFF' via Home Assistant

### ISSUE THREAD

**Issue by lewisbennett** [JeffSteinbok/hass-dreo#222]
Steps taken from Home Assistant booting up on freshly configured device.

* With the heater in the 'OFF' state, set to any state besides 'OFF' - the heater responds as expected
* Set the heater to the 'OFF' state and wait for the cooldown to elapse
* Set the heater to any state besides 'OFF' **<== the heater does not change to the requested state**

While in the erroneous state;
* the heater only displays a white WiFi symbol on the front that switches off once the state is once again set to 'OFF',
* the Dreo app is also unable to set the state of the heater.

I am able to make the heater responsive again by pressing the physical 'mode' button while the heater is configured to be in any state other than 'OFF'. It then works fine via Home Assistant and the Dreo app, until Home Assistant is used to set it to the 'OFF' state again.

The heater works fine with the Dreo app, just this one bit in Home Assistant that means I can't use it.

Heater model: **DR-HSH006S**
Heater firmware version: **V3.2.6_1.2.3**

[home-assistant_2024-10-29T13-32-13.302Z.log](https://github.com/user-attachments/files/17557883/home-assistant_2024-10-29T13-32-13.302Z.log)

**Comment by Gavin-A92** [comment]
I'm having the same/similar issue with a DR-HSH006S I setup yesterday.....there is a note/sticker on the top of the heater that says app control will be restricted under "certain situations" and the wifi light will illuminate as you describe above. The note goes on to reference some UK1278 Standard....haven't figured out exactly what the means yet....

Based on your post my own tests would seem to indicate that as you say the issue only arises when set to "Off" from within HA...you can turn On and Off from the App no problem but Off in HA causes the issue. Assuming not set to Off in HA all other functions work fine.
A workaround for now is in HA to set back to Eco Mode with a very low temp so the Heater is effectively off but doesn't lose connectivity to HA.....

**Comment by lewisbennett** [comment]
I spotted the sticker, and the readme does [make reference to the UL... standard](https://github.com/JeffSteinbok/hass-dreo#:~:text=Note%20that%20for,this%20HA%20integration.) too, though I don't believe this is being triggered in this case (at least not via the way described). The sticker does indeed mention that the light is supposed to illuminate yellow, though I can confirm it is very much white in this case.

It does indeed seem to only lie with setting the heater to the 'OFF' state as you can seemingly operate it however you want until turning it off, then manual intervention is required. Your workaround for switching it off via eco mode is genius btw, thank you!

As for Celsius for the current temperature, mine is also locked in Fahrenheit despite using Celsius in Home Assistant. The configured temperature on the heater entity shows in Celsius, but not the current temperature. The target temperature entity is also locked in Fahrenheit.

**Comment by AlexLemminG** [comment]
pull request with possible fix: #226
tested on a different device (DR-HSH004S), but I expect it to work for DR-HSH006S  as well

**Comment by chris4824** [comment]
@AlexLemminG 

This commit breaks my heaters. With this if you power off the heater with HA and then power it on by pressing button on heater or using dreo app, it will not show as being on in HA. You have to reload the integration or restart HA.

Models affected
DR-HSH009S

However it does seem to fix model DR-HSH017S which I also have. Is there another way to implement this?

**Comment by chris4824** [comment]
@AlexLemminG 

actually having a different issue that I thought was related but I do not think so now
#248

**Comment by chris0101** [comment]
I'm getting the issue with turning off via home assistant kills the heater ? Is this fixed?

**Comment by chris4824** [comment]
@chris0101 That issue has been fixed by @AlexLemminG and has been merged. But it has not made it to release yet. You can copy the code and fix it yourself until Jeff releases a new version with the fix.

**Comment by chris0101** [comment]
I did try that, it still doesn't seem to work for me, I'm likely doing
something wrong...

**Comment by chris4824** [comment]
Yeah. I was that issue and it fixed it for me. You restarted HA afterwards?.

**Comment by chris0101** [comment]
I did, I'll try again and get back to you

**Comment by chris0101** [comment]
So i've edited  " /homeassistant/custom_components/dreo/pydreo/pydreoheater.py " 

to show this 

"  @mode.setter
    def mode(self, mode: str) -> None:
        _LOGGER.debug("PyDreoHeater:mode(%s) --> %s", self.name, mode)
        # setting heater mode to OFF is redundand because 'poweron' will be set
        # and can prevent it from properly turning back on (tested on DR-HSH004S)
        if not mode == HEATER_MODE_OFF:
            self._send_command(MODE_KEY, mode)
"

This is between the lines of 170 - 176,  i've restarted homeassistant but still getting no joy, just unresponsive.

**Comment by chris4824** [comment]
@chris0101 looks correct as long as the indentions are correct. If so, someone smarter than I am will have to help. Maybe @AlexLemminG  can take a look. May want to include debug log.

**Comment by chris0101** [comment]
After you mentioned about the spacing I deleted and copied the entire file.

Working now ! My mistake !

**Comment by chris4824** [comment]
Awesome. Glad you got it working..
